### ISSUE TITLE
MCUXpresso derivation launches with "Invalid or incompatible LinkServer configured" error

### ISSUE THREAD

**Issue by nezia1** [KoviRobi/nixos-config#1]
Hey, I saw that you packaged MCUXpresso for NixOS. Thanks a ton by the way, I'm using it for school and I needed something functional. However, when launching it I get an error: 
![image](https://github.com/user-attachments/assets/1050c0a4-8605-43e2-b6b3-62d012c3ea64)

This makes it impossible to debug on my card unfortunately. It also complains about "unable to find dfu-util" when trying to debug? Do you have any clue why that might be caused? These are the full logs for the error:
```
Internal: unable to find dfu-util

Internal: unable to find dfu-util
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.emulators.AbstractCommonDFUProbe.getDfuCommand(AbstractCommonDFUProbe.java:123)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.emulators.AbstractCommonDFUProbe.getAllDfuVidPids(AbstractCommonDFUProbe.java:105)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.emulators.AbstractCommonBootableProbe.getMyDfuVidPids(AbstractCommonBootableProbe.java:310)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.emulators.AbstractCommonBootableProbe.getNumDfus(AbstractCommonBootableProbe.java:339)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.emulators.AbstractCommonBootableProbe.requiresBoot(AbstractCommonBootableProbe.java:436)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.emulators.EmulatorsDB.getEmulatorInfo(EmulatorsDB.java:187)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.emulators.EmulatorsDB.getAvailableEmulators(EmulatorsDB.java:139)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.emulators.TargetDiscovery.getAvailableEmulators(TargetDiscovery.java:508)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.launch.LinkServerLaunchConfigHandler.probeDiscovery(LinkServerLaunchConfigHandler.java:631)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.launch.LinkServerLaunchConfigHandler.checkProbe(LinkServerLaunchConfigHandler.java:948)
  	at com.nxp.mcuxpresso.core.debug.launch.AbstractNXPLaunchConfigHandler.promptDiscovery(AbstractNXPLaunchConfigHandler.java:1268)
  	at com.nxp.mcuxpresso.core.debug.launch.AbstractNXPLaunchConfigHandler.createMissingLaunchConfigurations(AbstractNXPLaunchConfigHandler.java:1394)
  	at com.nxp.mcuxpresso.core.debug.support.linkserver.launch.LinkServerLaunchConfigHandler.createMissingLaunchConfigurations(LinkServerLaunchConfigHandler.java:494)
  	at com.nxp.mcuxpresso.core.debug.launch.NXPLaunchConfigUtils.createMissingLaunchConfigurations(NXPLaunchConfigUtils.java:360)
  	at com.nxp.mcuxpresso.core.debug.launch.NXPLaunchConfigUtils.createMissingLaunchConfigurations(NXPLaunchConfigUtils.java:441)
  	at com.nxp.mcuxpresso.core.debug.launch.NXPLaunchConfigUtils.createLaunchConfigurations(NXPLaunchConfigUtils.java:985)
  	at com.crt.quickstart.utils.QSUtilDebug.linkSelected(QSUtilDebug.java:257)
  	at com.crt.quickstart.views.links.QSDebug.linkSelected(QSDebug.java:98)
  	at com.crt.quickstart.views.links.ui.QSLinkAction$2.run(QSLinkAction.java:139)
  	at com.crt.quickstart.views.links.ui.QSExpandBarSection$4.linkActivated(QSExpandBarSection.java:294)
  	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:215)
  	at org.eclipse.ui.forms.widgets.ImageHyperlink.handleActivate(ImageHyperlink.java:212)
  	at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:309)
  	at org.eclipse.ui.forms.widgets.AbstractHyperlink.lambda$3(AbstractHyperlink.java:117)
  	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
  	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5854)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
  	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5064)
  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4516)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
  	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
  	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
  	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
  	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
  	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
  	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
  	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
```

No debugging logs in the terminal unfortunately. All I'm getting is graphical warnings:
```
➜ mcuxpresso
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Toolbar: com.crt.quickstart.toolbar in menu:com.crt.quickstart.toolbar

(MCUXpresso IDE:525366): Gtk-CRITICAL **: 16:13:48.873: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed
Arguments: 

Arguments: 

log4j:WARN No appenders could be found for logger (org.eclipse.xtext.ui.internal.Activator).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by KoviRobi** [comment]
Yes, there's a separate linkserver thing that comes with MCUXpresso that I haven't packaged because I didn't need it (I flash using a JLink from the command line).

For the dfu-util you could either try to add it to the derivation, or install it on your system, depending on where the Eclipse looks for it

**Comment by nezia1** [comment]
Do you have any clue/pointers on how I could add it to the derivation? I tried taking a stab at it but I don't understand the internal structure of the archive. 

> For the dfu-util you could either try to add it to the derivation, or install it on your system, depending on where the Eclipse looks for it

Added it to my system and it just worked OOTB :) now there's only linkserver that's needed.

**Comment by KoviRobi** [comment]
> Do you have any clue/pointers on how I could add it to the derivation? I tried taking a stab at it but I don't understand the internal structure of the archive.

I'll try to have a look later when I'm on my desktop, but tbh I just found the eclipse hints on nixos discourse somewhere

**Comment by nezia1** [comment]
If you're interested, I started working on it a little bit. Here's what I have for the build phase:
```
    buildCommand = ''
      # Unpack tarball.
      mkdir -p deb
      sh $src --target deb || true
      ar -xv deb/${filename}
      tar xfvz data.tar.gz -C .

      # Unpack LinkServer.
      mkdir -p linkserver
      sh deb/LinkServer_24.9.75.x86_64.deb.bin --target deb/linkserver || true
      ar -xv deb/linkserver/LPCScrypt.deb
      tar xfvz data.tar.gz -C linkserver
      ar -xv deb/linkserver/MCU-Link.deb
      tar xfvz data.tar.gz -C linkserver
      ar -xv deb/linkserver/LinkServer_24.9.75.x86_64.deb
      tar xfvz data.tar.gz -C linkserver

      mkdir -p ./final/eclipse
      mv ./usr/local/${name}-${version}/ide/* ./usr/local/${name}-${version}/ide/.* final/eclipse
      mv final/eclipse/mcuxpressoide final/eclipse/eclipse
      mv final/eclipse/mcuxpressoide.ini final/eclipse/eclipse.ini

      # Create custom .eclipseproduct file
      rm final/eclipse/.eclipseproduct
      echo "name=${name}
      id=com.nxp.${name}
      version=${version}
      " > final/eclipse/.eclipseproduct

      # Install udev rules
      mkdir -p final/lib/udev/rules.d
      mv ./lib/udev/rules.d/56-pemicro.rules ./lib/udev/rules.d/85-mcuxpresso.rules final/lib/udev/rules.d/

      # Additional files
      mv ./usr/local/${name}-${version}/mcu_data final/mcu_data

      # Place LinkServer, lpcscrypt, and MCU-LINK_installer in /usr/local
      mkdir -p ./final/usr/local
      mv ./linkserver/usr/local/LinkServer_24.9.75 ./final/usr/local/linkserver
      mv ./linkserver/usr/local/lpcscrypt-2.1.3_83 ./final/usr/local/lpcscrypt
      mv ./linkserver/usr/local/MCU-LINK_installer_3.148 ./final/usr/local/MCU-LINK_installer

      # Install LinkServer udev rules
      # mv ./linkserver/lib/udev/rules.d/{85-linkserver_24.9.75.rules,85-mcu-link_3.148.rules,99-lpcscrypt.rules} final/lib/udev/rules.d

      cd ./final
      tar -czf $out ./
    '';
```

This almost works, but I think I might be missing a few symlinks here and there. This is what the `/usr/local` looks like under a regular MCUXpresso install (installed from the `.bin`): 
```
[I] nezia@vamos /u/local> ls -al
total 64
drwxr-xr-x 1 root  root 4096 Nov  3 17:05 ./
drwxr-xr-x 1 root  root 4096 Nov  3 17:03 ../
lrwxrwxrwx 1 root  root   29 Nov  3 17:05 LinkServer -> /usr/local/LinkServer_24.9.75/
drwxr-xr-x 9 nezia root 4096 Nov  3 17:05 LinkServer_24.9.75/
lrwxrwxrwx 1 root  root   35 Nov  3 17:05 MCU-LINK_installer -> /usr/local/MCU-LINK_installer_3.148/
drwxr-xr-x 7 root  root 4096 Nov  3 17:05 MCU-LINK_installer_3.148/
drwxr-xr-x 1 root  root 4096 Nov  3 17:04 bin/
drwxr-xr-x 2 root  root 4096 Oct 11 02:03 etc/
drwxr-xr-x 2 root  root 4096 Oct 11 02:03 games/
drwxr-xr-x 2 root  root 4096 Oct 11 02:03 include/
drwxr-xr-x 1 root  root 4096 Nov  3 17:04 lib/
lrwxrwxrwx 1 root  root   29 Nov  3 17:05 lpcscrypt -> /usr/local/lpcscrypt-2.1.3_83/
drwxr-xr-x 8 root  root 4096 Nov  3 17:05 lpcscrypt-2.1.3_83/
lrwxrwxrwx 1 root  root    9 Oct 11 02:03 man -> share/man/
lrwxrwxrwx 1 root  root   32 Nov  3 17:05 mcuxpressoide -> /usr/local/mcuxpressoide-24.9.25/
drwxr-xr-x 6 root  root 4096 Nov  3 17:05 mcuxpressoide-24.9.25/
drwxr-xr-x 2 root  root 4096 Oct 11 02:09 sbin/
drwxr-xr-x 1 root  root 4096 Nov  3 17:03 share/
drwxr-xr-x 2 root  root 4096 Oct 11 02:03 src/
[I] nezia@vamos /u/local> pwd
/usr/local
```

I think we might need to symlink dependencies somewhere. This is how I've set them up in `mcuxpressoide`, under `/usr/local`:
```
➜ ls
linkserver/  lpcscrypt/  MCU-LINK_installer/
``` 

But that doesn't seem to work, so I'm not sure where we need to place this `LinkServer` and its respective dependencies.

**Comment by nezia1** [comment]
> I think we might need to symlink dependencies somewhere. This is how I've set them up in mcuxpressoide, under /usr/local:

This very likely needs to go into the final derivation instead, not `mcuxpressoide`. I just noticed that

**Comment by KoviRobi** [comment]
> > I think we might need to symlink dependencies somewhere. This is how I've set them up in mcuxpressoide, under /usr/local:
> 
> This very likely needs to go into the final derivation instead, not `mcuxpressoide`. I just noticed that

Yes I suspect it needs to be somewhere Eclipse can find it. You could try just setting it with

![image](https://github.com/user-attachments/assets/d025b654-6c3c-4c76-8f38-461c86c6fb8e)

Or move it into the `src` derivation, `final/eclipse/plugins/com.nxp.mcuxpresso.tools.linux_24.9.0.202407110857/` somewhere.

I'm heading off to a new year's party, but looks like you have some ideas worth investigating, happy hacking (or partying -- but it's not like I haven't also in the past spent celebration time coding)!

**Comment by nezia1** [comment]
Happy new years! So this might get a little more difficult:
```
➜ ./LinkServer 
Could not start dynamically linked executable: ./LinkServer
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```
I also tried setting the path to this directory, but MCUXpresso told me that it was not a valid LinkServer root directory.

**Comment by nezia1** [comment]
Good progress has been made! I have managed to fix some dependencies (you can find my derivation [here](https://github.com/nezia1/flocon/blob/main/shared/pkgs/mcuxpresso/ide.nix)). Now for the error I'm running into, it seems that

**Comment by KoviRobi** [comment]
Indeed the FHS env is *one* way to solve it, there is also autopatchelf which runs during the fixup phase, see https://nixos.org/manual/nixpkgs/stable/#setup-hook-autopatchelfhook -- this uses `patchelf` to change the ELF  RUNPATH to include the Nix location for the given libraries.

**Comment by KoviRobi** [comment]
> I also tried setting the path to this directory, but MCUXpresso told me that it was not a valid LinkServer root directory.

Possibly mcuxpresso expects it to be a directory structure like

<details>
<summary>

    ❯ tar tf data.tar.gz | sed -n 's+usr/local/\(.*/\)$+\1+p'

</summary>

```
LinkServer_24.9.75/
LinkServer_24.9.75/binaries/
LinkServer_24.9.75/binaries/coresight/
LinkServer_24.9.75/binaries/power/
LinkServer_24.9.75/binaries/Flash/
LinkServer_24.9.75/binaries/Scripts/
LinkServer_24.9.75/binaries/ToolScripts/
LinkServer_24.9.75/licenses/
LinkServer_24.9.75/Wizards/
LinkServer_24.9.75/Wizards/linker/
LinkServer_24.9.75/docs/
LinkServer_24.9.75/docs/assets/
LinkServer_24.9.75/docs/images/
LinkServer_24.9.75/docs/images/linkflash/
LinkServer_24.9.75/dist/
LinkServer_24.9.75/dist/_internal/
LinkServer_24.9.75/dist/_internal/_tcl_data/
LinkServer_24.9.75/dist/_internal/_tcl_data/http1.0/
LinkServer_24.9.75/dist/_internal/_tcl_data/msgs/
LinkServer_24.9.75/dist/_internal/_tcl_data/encoding/
LinkServer_24.9.75/dist/_internal/_tcl_data/opt0.4/
LinkServer_24.9.75/dist/_internal/_tcl_data/tcl8/
LinkServer_24.9.75/dist/_internal/_tcl_data/tcl8/platform/
LinkServer_24.9.75/dist/_internal/jsonschema/
LinkServer_24.9.75/dist/_internal/jsonschema/schemas/
LinkServer_24.9.75/dist/_internal/_tk_data/
LinkServer_24.9.75/dist/_internal/_tk_data/ttk/
LinkServer_24.9.75/dist/_internal/_tk_data/msgs/
LinkServer_24.9.75/dist/_internal/_tk_data/images/
LinkServer_24.9.75/dist/_internal/jsonschema-4.4.0.dist-info/
LinkServer_24.9.75/dist/_internal/tkinterdnd2/
LinkServer_24.9.75/dist/_internal/tkinterdnd2/tkdnd/
LinkServer_24.9.75/dist/_internal/tkinterdnd2/tkdnd/linux-x64/
LinkServer_24.9.75/dist/_internal/tkinterdnd2/tkdnd/linux-arm64/
LinkServer_24.9.75/dist/_internal/lib-dynload/
LinkServer_24.9.75/dist/_internal/res/
LinkServer_24.9.75/Examples/
LinkServer_24.9.75/Examples/Misc/
LinkServer_24.9.75/Examples/Flashdrivers/
LinkServer_24.9.75/Examples/Flashdrivers/NXP/
LinkServer_24.9.75/Examples/Flashdrivers/NXP/LPC18_43/
LinkServer_24.9.75/Examples/Flashdrivers/NXP/LPC55xx/
LinkServer_24.9.75/Examples/Flashdrivers/NXP/LPC5460x/
LinkServer_24.9.75/Examples/Flashdrivers/NXP/K32W/
LinkServer_24.9.75/Examples/Flashdrivers/NXP/iMXRT/
LinkServer_24.9.75/Examples/Flashdrivers/NXP/LPC40xx/
LinkServer_24.9.75/Examples/Flashdrivers/NXP/RW61x/
LinkServer_24.9.75/Examples/Flashdrivers/NXP/MCXN9xx/
LinkServer_24.9.75/devices/
```
</details>

**Comment by nezia1** [comment]
> Indeed the FHS env is _one_ way to solve it, there is also autopatchelf which runs during the fixup phase, see https://nixos.org/manual/nixpkgs/stable/#setup-hook-autopatchelfhook -- this uses `patchelf` to change the ELF RUNPATH to include the Nix location for the given libraries.

Oh that is actually a good idea. I might try that. I'm pretty sure I'm almost done, however some binaries still don't work because they require Python 3.8 to be available in the environment, which is.. Not possible if using `nixos-unstable`. Is there a way to possibly overlay nixpkgs just for Python 3.8? I don't know if you can actually do that in a derivation.

**Comment by nezia1** [comment]
Also, do we even need `buildEclipse` at all? That's something else entirely but I was wondering.

**Comment by KoviRobi** [comment]
> Python 3.8 to be available in the environment

You could just add a compatibility symlink, any python3 should work I expect

> do we even need buildEclipse at all?

I would expect so, haven't checked, this is what it does

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/eclipse/build-eclipse.nix
